export const SET_RESERVATION_DATE = 'SET_RESERVATION_DATE'
export const SET_RESERVATION_OWNER_EMAIL = 'SET_RESERVATION_OWNER_EMAIL'
export const ADD_TABLE_TO_RESERVATION = 'ADD_TABLE_TO_RESERVATION'
export const REMOVE_TABLE_FROM_RESERVATION = 'REMOVE_TABLE_FROM_RESERVATION'