version: 2
jobs:
 build:
  docker:
    - image: circleci/node:8
  steps:
    - run:
        name: Setup environment
        command: npm install gh-pages
    - test:
        name: Run tests
        command: npm test
    - deploy:
        name: Build and push to GithubPages
        command: npm run deploy
