version: 2
jobs:
 build:
  branches:
   ignore:
    - gh-pages
  docker:
    - image: circleci/node:8
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
    - run:
        name: Install dependencies
        command: npm install
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}  
    - deploy:
        name: Build and push to GithubPages
        command: | 
          git config --global user.email $GH_EMAIL
          git config --global user.name $GH_NAME
          CI=false npm run deploy 
