version: 2
jobs:
 build:
  docker:
    - image: circleci/node:8
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: npm install
    - deploy:
        name: Build and push to GithubPages
        command: | 
          git config --global user.email $GH_EMAIL
          git config --global user.name $GH_NAME
          npm run deploy
