version: 2
jobs:
 build:
  docker:
    - image: circleci/node:8
  working_directory: ~/repo
  steps:
    - run:
        name: Setup environment
        command: npm install gh-pages
    - deploy:
        name: Build and push to GithubPages
        command: npm run deploy
